//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobone.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cobone.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string account_menu_credit {
            get {
                return ResourceManager.GetString("account-menu-credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string account_menu_logout {
            get {
                return ResourceManager.GetString("account-menu-logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string account_menu_order {
            get {
                return ResourceManager.GetString("account-menu-order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string account_menu_settings {
            get {
                return ResourceManager.GetString("account-menu-settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string appbar_account_text {
            get {
                return ResourceManager.GetString("appbar_account_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string appbar_account_unauthorized_text {
            get {
                return ResourceManager.GetString("appbar_account_unauthorized_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string appbar_cart_text {
            get {
                return ResourceManager.GetString("appbar_cart_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Offers.
        /// </summary>
        public static string appbar_offer_text {
            get {
                return ResourceManager.GetString("appbar_offer_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you looking for?.
        /// </summary>
        public static string appbar_search_text {
            get {
                return ResourceManager.GetString("appbar-search-text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string checkout {
            get {
                return ResourceManager.GetString("checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Shopping.
        /// </summary>
        public static string continue_shopping {
            get {
                return ResourceManager.GetString("continue-shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abous us.
        /// </summary>
        public static string footer_about_us {
            get {
                return ResourceManager.GetString("footer-about-us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY.
        /// </summary>
        public static string footer_company {
            get {
                return ResourceManager.GetString("footer-company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string footer_contact_us {
            get {
                return ResourceManager.GetString("footer-contact-us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service.
        /// </summary>
        public static string footer_customer_service {
            get {
                return ResourceManager.GetString("footer-customer-service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD OUR APP.
        /// </summary>
        public static string footer_download {
            get {
                return ResourceManager.GetString("footer-download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string footer_facebook {
            get {
                return ResourceManager.GetString("footer-facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string footer_how_it_work {
            get {
                return ResourceManager.GetString("footer-how-it-work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to buy.
        /// </summary>
        public static string footer_how_to_buy {
            get {
                return ResourceManager.GetString("footer-how-to-buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to pay.
        /// </summary>
        public static string footer_how_to_pay {
            get {
                return ResourceManager.GetString("footer-how-to-pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string footer_instagram {
            get {
                return ResourceManager.GetString("footer-instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARN MORE.
        /// </summary>
        public static string footer_learn_more {
            get {
                return ResourceManager.GetString("footer-learn-more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEET US.
        /// </summary>
        public static string footer_meet_us {
            get {
                return ResourceManager.GetString("footer-meet-us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDIT / DEBIT CARDS.
        /// </summary>
        public static string footer_payment {
            get {
                return ResourceManager.GetString("footer-payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string footer_privacy_policy {
            get {
                return ResourceManager.GetString("footer-privacy-policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string footer_terms_conditions {
            get {
                return ResourceManager.GetString("footer-terms-conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string forgot_password_email {
            get {
                return ResourceManager.GetString("forgot-password-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string forgot_password_reset {
            get {
                return ResourceManager.GetString("forgot-password-reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Seller.
        /// </summary>
        public static string index_best_seller {
            get {
                return ResourceManager.GetString("index_best_seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string index_latest {
            get {
                return ResourceManager.GetString("index_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string index_special {
            get {
                return ResourceManager.GetString("index_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string login_email {
            get {
                return ResourceManager.GetString("login-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string login_forgot {
            get {
                return ResourceManager.GetString("login-forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a strong password.
        /// </summary>
        public static string login_helper {
            get {
                return ResourceManager.GetString("login-helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login_login {
            get {
                return ResourceManager.GetString("login-login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string login_password {
            get {
                return ResourceManager.GetString("login-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not registered yet. click here.
        /// </summary>
        public static string login_register {
            get {
                return ResourceManager.GetString("login-register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        public static string order_summary {
            get {
                return ResourceManager.GetString("order-summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string order_total {
            get {
                return ResourceManager.GetString("order-total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string payment_method {
            get {
                return ResourceManager.GetString("payment-method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        public static string percentage_off {
            get {
                return ResourceManager.GetString("percentage-off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TO CART.
        /// </summary>
        public static string product_info_add_to_cart {
            get {
                return ResourceManager.GetString("product-info-add-to-cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE YOUR OPTION.
        /// </summary>
        public static string product_info_option {
            get {
                return ResourceManager.GetString("product-info-option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUICK CHECKOUT.
        /// </summary>
        public static string product_info_quick_checkout {
            get {
                return ResourceManager.GetString("product-info-quick-checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this deal:.
        /// </summary>
        public static string product_info_share_deal {
            get {
                return ResourceManager.GetString("product-info-share-deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string register_confirm_password {
            get {
                return ResourceManager.GetString("register-confirm-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the password.
        /// </summary>
        public static string register_confirm_password_helper {
            get {
                return ResourceManager.GetString("register-confirm-password-helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string register_email {
            get {
                return ResourceManager.GetString("register-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Email.
        /// </summary>
        public static string register_email_invalid_message {
            get {
                return ResourceManager.GetString("register-email-invalid-message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string register_first_name {
            get {
                return ResourceManager.GetString("register-first-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string register_last_name {
            get {
                return ResourceManager.GetString("register-last-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string register_password {
            get {
                return ResourceManager.GetString("register-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a strong password.
        /// </summary>
        public static string register_password_helper {
            get {
                return ResourceManager.GetString("register-password-helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password doesn&apos;t match.
        /// </summary>
        public static string register_password_match_message {
            get {
                return ResourceManager.GetString("register-password-match-message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string register_phone {
            get {
                return ResourceManager.GetString("register-phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        public static string register_phone_helper {
            get {
                return ResourceManager.GetString("register-phone-helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid phone number.
        /// </summary>
        public static string register_phone_invalid_message {
            get {
                return ResourceManager.GetString("register-phone-invalid-message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register_register {
            get {
                return ResourceManager.GetString("register-register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string register_required_message {
            get {
                return ResourceManager.GetString("register-required-message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, the item is out of stock.
        /// </summary>
        public static string unavailable {
            get {
                return ResourceManager.GetString("unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW DEAL.
        /// </summary>
        public static string view_deal {
            get {
                return ResourceManager.GetString("view-deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Shopping Cart.
        /// </summary>
        public static string your_shopping_cart {
            get {
                return ResourceManager.GetString("your-shopping-cart", resourceCulture);
            }
        }
    }
}
